apiVersion: v1
kind: Service
metadata:
  name: search-app-2-service
spec:
  selector:
    app: search-app-2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3001
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: nodejs-search-app-2
  labels:
    app: search-app-2
spec:
  containers:
    - name: search-app-2-container
      image: jrodriguezdiazz/search-app-2
      ports:
        - containerPort: 3001
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-search-app-2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-app-2
  template:
    metadata:
      labels:
        app: search-app-2
    spec:
      containers:
        - name: search-app-2-container
          image: jrodriguezdiazz/search-app-2:latest
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
