apiVersion: v1
kind: Service
metadata:
  name: search-app-1-service
spec:
  selector:
    app: search-app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: nodejs-search-app-1
  labels:
    app: search-app-1
spec:
  containers:
    - name: search-app-1-container
      image: jrodriguezdiazz/search-app-1
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-search-app-1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-app-1
  template:
    metadata:
      labels:
        app: search-app-1
    spec:
      containers:
        - name: search-app-1-container
          image: jrodriguezdiazz/search-app-1:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
