apiVersion: v1
kind: Pod
metadata:
  name: nodejs-search-app-1
  labels:
    app: search-app-1
spec:
  containers:
    - name: search-app-1-container
      image: jrodriguezdiazz/search-app-1
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

---
apiVersion: v1
kind: Pod
metadata:
  name: nodejs-search-app-2
  labels:
    app: search-app-2
spec:
  containers:
    - name: search-app-2-container
      image: jrodriguezdiazz/search-app-2
      ports:
        - containerPort: 3001
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
