apiVersion: v1
kind: Service
metadata:
  name: search-apps-service
spec:
  selector:
    app: search-app
  ports:
    - name: port1
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: port2
      protocol: TCP
      port: 3001
      targetPort: 3001
