apiVersion: v1
kind: Service
metadata:
  name: search-apps-service
spec:
  selector:
    app: search-app
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port2
      protocol: TCP
      port: 8081
      targetPort: 8081
